package sample.Controller;

import com.mysql.cj.xdevapi.Table;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;
import sample.DAO.JDBC;
import sample.model.appointment;
import sample.model.reporter;

import java.io.IOException;
import java.sql.SQLException;

public class reportController{
    public TableView reportTable;

    /** This method generates a report on the total number of customer appointments by type and month. Information is retrieved via the reporter class and displayed in a TableView.
     *
     * @param actionEvent Triggered upon pressing the view reports button.
     * @throws SQLException
     */
    public void viewAllAppointments(ActionEvent actionEvent) throws SQLException {
        reportTable.getColumns().clear();

        ObservableList<String> listReport = FXCollections.observableArrayList();
        JDBC.openConnection();
        listReport = reporter.getAppointmentReport();
        JDBC.closeConnection();

        /** This lambda expression populates columns. As the TableView only has one selected column with an ObservableList containing only simple strings, a method to convert strings to displayable data was required.
         *
         */
        TableColumn<String, String> totalCol = new TableColumn("Information");
        totalCol.setCellValueFactory(data -> {
            String value = data.getValue();
            return new SimpleStringProperty(value);
        });

        reportTable.setItems(listReport);
        reportTable.getColumns().add(totalCol);
    }

    /** This method generates a report on the appointments for each contact and sorts them by contact ID. Information is retrieved and displayed in a TableView.
     *
     * @param actionEvent Triggered upon pressing the view contact report button.
     * @throws SQLException
     */
    public void viewContactAppointments(ActionEvent actionEvent) throws SQLException {
        // clear table
        reportTable.getColumns().clear();

        ObservableList<appointment> listAppointment = FXCollections.observableArrayList();
        JDBC.openConnection();
        listAppointment = reporter.getContactAppointments();
        JDBC.closeConnection();

        reportTable.setItems(listAppointment);
        TableColumn appContCol = new TableColumn("Contact ID");
        TableColumn appAIDCol = new TableColumn("Appointment ID");
        TableColumn appTitleCol = new TableColumn("Title");
        TableColumn appTypeCol = new TableColumn("Type");
        TableColumn appDesCol = new TableColumn("Description");
        TableColumn appStartCol = new TableColumn("Start");
        TableColumn appEndCol = new TableColumn("End");
        TableColumn appCIDCol = new TableColumn("Customer ID");
        reportTable.getColumns().addAll(appContCol, appAIDCol, appTitleCol, appTypeCol, appDesCol, appStartCol, appEndCol, appCIDCol);

        appContCol.setCellValueFactory(new PropertyValueFactory<>("contactID"));
        appAIDCol.setCellValueFactory(new PropertyValueFactory<>("appointmentID"));
        appTitleCol.setCellValueFactory(new PropertyValueFactory<>("title"));
        appTypeCol.setCellValueFactory(new PropertyValueFactory<>("appointmentType"));
        appDesCol.setCellValueFactory(new PropertyValueFactory<>("description"));
        appStartCol.setCellValueFactory(new PropertyValueFactory<>("appointmentStart"));
        appEndCol.setCellValueFactory(new PropertyValueFactory<>("appointmentEnd"));
        appCIDCol.setCellValueFactory(new PropertyValueFactory<>("customerID"));
    }

    /** This method generates a report of all the appointments that have been generated by a user and sorts the creation rate by date. Information is retrieved via the reporter class and displayed in a TableView.
     *
     * @param actionEvent Triggered upon pressing the customer creation report button.
     * @throws SQLException
     */
    public void viewCreation(ActionEvent actionEvent) throws SQLException {
        reportTable.getColumns().clear();

        ObservableList<String> listCreation = FXCollections.observableArrayList();
        JDBC.openConnection();
        listCreation = reporter.getCreationActivity();
        JDBC.closeConnection();

        TableColumn<String, String> totalCol = new TableColumn("Information");
        /** This lambda expression populates columns. As the TableView only has one selected column with an ObservableList containing only simple strings, a method to convert strings to displayable data was required.
         *
         */
        totalCol.setCellValueFactory(data -> {
            String value = data.getValue();
            return new SimpleStringProperty(value);
        });

        reportTable.setItems(listCreation);
        reportTable.getColumns().add(totalCol);
    }

    /** This method returns the user to the main menu.
     *
     * @param actionEvent Triggers upon pressing the exit button.
     * @throws IOException
     */
    public void returnMenu(ActionEvent actionEvent) throws IOException {
        Parent root = FXMLLoader.load(getClass().getResource("/sample/view/menuScreen.fxml"));
        Stage stage = new Stage();
        Scene scene = new Scene(root, 400, 400);
        stage.setTitle ("Main Menu");
        stage.setScene(scene);
        stage.show();

        Stage prevStage = (Stage) reportTable.getScene().getWindow();
        prevStage.close();
    }
}
